name: Jira Deployment

on:
  workflow_dispatch:
    inputs:
      docker_image_version:
        description: 'docker image version deployed'
        required: true
      environment:
        description: 'environment were deployment was made'
        required: true
      result:
        description: 'deployment result (code may be deployed but deployment went on failure)'
        required: false

jobs:
  deployment:
    name: Release deployed to environment
    runs-on: [microservices2]
    env:
      MICROSERVICE: sam-assetmgt-api
    steps:
         
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Clone private actions
      uses: actions/checkout@v2
      with:
        repository: eriksdigital/github-actions
        token: ${{ secrets.PAT }}
        path: ./.github/actions/github-actions
        
    - name: Extract last commit message
      id: deployment_extract_last_commit
      shell: bash
      run: |
        echo "##[set-output name=message;]$(git log $tag --format=%B -n 1 | head -n 1)"
      env:
        tag: ${{ github.event.inputs.docker_image_version }}

    - name: Login Jira cloud
      uses: atlassian/gajira-login@master
      env:
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_BASE_URL: ${{ secrets.JIRA_URL }}

    - name: Find Jira ticket code in branch
      id: deployment_jira_issue
      uses: atlassian/gajira-find-issue-key@master
      with:
        string: ${{ steps.deployment_extract_last_commit.outputs.message }}

    - name: Choose Jira transition to execute
      id: deployment_jira_in_transition
      run: |
        if [[ "$ENVIRONMENT" == "prod" ]]; then
            echo "##[set-output name=transition;]Done"
        elif [[ "$ENVIRONMENT" == "accp" ]]; then
            echo "##[set-output name=transition;]Acceptance"
        elif [[ "$ENVIRONMENT" == "dev" ]]; then
            echo "##[set-output name=transition;]Test"
        fi
      env:
        ENVIRONMENT: ${{ github.event.inputs.environment }}

    - name: Transition Jira ticket from deployment
      uses: ./.github/actions/github-actions/sam-jira-transition
      with: 
        jira_username: ${{ secrets.JIRA_USERNAME }}
        jira_token: ${{ secrets.JIRA_TOKEN }}
        jira_url: ${{ secrets.JIRA_URL }}
        jira_transition: ${{ steps.deployment_jira_in_transition.outputs.transition }}
        jira_issue_related: ${{ steps.deployment_jira_issue.outputs.issue }}
        component_name: ${{ env.MICROSERVICE }}
        version: ${{ github.event.inputs.docker_image_version }}
        deploy_result: ${{ github.event.inputs.result }}