name: FRONTEND

on:
  workflow_call:
    inputs:
      MICROSERVICE:
        description: 'The name of the service'
        required: true
        type: string
        default: 'latest'
  push:
    branches: [ $default-branch,hotfix-*  ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  ci:
    runs-on: [microservices2]
    env:
      AWX_STACK_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo hello I'm test workflow
