name: FRONTEND

on:
  push:
    branches: [ $default-branch,hotfix-*  ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  ci:
    runs-on: [microservices2]
    env:
      MICROSERVICE: ${{ github.repository }}
      AWX_STACK_NAME: ${{ github.repository }}

    steps:
    - name: Permission fix
      shell: bash
      run: sudo chown -R automation:automation .
      
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        ref: ${{ github.ref }}
        fetch-depth: 0
