name: Test CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: microservices2

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo hello I'm test workflow
