name: FRONTEND

on:
  push:
    branches: [ $default-branch,hotfix-*  ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  ci:
    runs-on: [microservices2]
    env:
      MICROSERVICE: $repo
      AWX_STACK_NAME: $repo

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo hello I'm test workflow
